version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: boa-lamp:latest
    container_name: boa-lamp
    environment:
      CREATE_MYSQL_BASIC_USER_AND_DB: "true"
      MYSQL_USER_DB: drupal
      MYSQL_USER_NAME: drupal
      MYSQL_USER_PASS: ''
      WWW_PUBLISHED_PORT: ${WWW_PUBLISHED_PORT:-3000}
      BOA_USER: ${BOA_USER:-boa}
      BOA_PW: ${BOA_PW:-rocks}
    ports:
      # Apache
      - published: ${WWW_PUBLISHED_PORT:-3000}
        target: 80
      # MySQL
      - published: ${SQL_PUBLISHED_PORT:-3001}
        target: 3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./data:/data
